### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by thetwopct** [vwochnik/jekyll-autoprefixer#10]
Hi, I wonder if this package is still working, and if it is, maybe I'm doing something wrong?

I've installed autoprefixer as a dependency

`npm i -D autoprefixer`

I've added 

`gem 'jekyll-autoprefixer'`

to my Gemfile

I've added

```
plugins:
  - jekyll-autoprefixer
```

and

```
  autoprefixer:
    only_production: false
    browsers:
    - last 2 versions
    - not dead
    - ie 10
```

to my _config.yml, as well as trying variations of running with/without autoprefixer flag.

CSS is still not being prefixed.

Any ideas?
